apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-simple
  namespace: uitest-a
  labels:
    app: uitest-simple
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: staging-uk-west/uitest-a/uitest-simple.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '30'
    portainer-idp/edge-group-ids: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-simple
  template:
    metadata:
      labels:
        app: uitest-simple
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: Always
