apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-std-sec2
  namespace: uitest-r11-std-ns-hdy
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-r11-std-tgt-kqz/secrets/uitest-r11-std-ns-hdy/uitest-r11-std-sec2.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '43'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    TOKEN: >-
      AgB1RJSY8phfmrlEJc09kZLCNTxKkHuqtGU++7ft2vGOJZ1ED+arZFdzpx/RTNZZleHgv/IBczUSo6LxR8HXc4blAW18zu3eUBrygMqavnlp+i2tbXQhiE+IghaGbQORcwiBbLvUTALJWGD9XoFAgHUdCNrP3HzkJ5eHA9qE6rkPL49GGp2qs0sfenvv6KcyA99dhIap6UsrNuQ7PIQveaU7+5hzGywZz3mA6CGuadBi0Tp4a4kvZaDBEWX0sz2/5YdoKWQQG5heT/V7/w+zQfNoQKvW8axR3Ey28UXjsJnrfz2Poq4TMoeoRUxhjS65VJCJtNuT2K5hWkqxGwjudz82oOmZmeGVNkmybfXv5NV9zVKjLOGhVhGGlSjchQxx+jDVpM75S3R/JFxdhzKNVOUpxb+U/NcJCZcgPre6hMmqQi0rFQDZTAYJcLn31zEFEYBjI6gGi7+Hig4pXzrXLWWG9w47vsLjFwp37iozJU2knKlBnh5TsZpHuhm1wjJQIpfiCJcuaf3GV+Rxrwet1OaSFqcyqf9Yr9wZV2hU42lIO5f2SrxsbYAUNF7hsrbPd4Pw7O4bGdS0byeldjJQnb2WGiVKWiAfwVy+NyOwKWyh74q3Ma6ZOFsL+SpF5mZ3l1fJDQFon2fK8FGegN1Na8uR8aveWK1U40Dd5PAREikTEV1C/LZJpfQVLGTEHP+CBkGKSrD8E9h3I7oSl3SJ2sqGnHHW1vxyYSBzDw==
  template:
    type: Opaque
    metadata:
      name: uitest-r11-std-sec2
      namespace: uitest-r11-std-ns-hdy
      labels:
        managed-by: portainer-idp
