apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-std-pg-auth
  namespace: uitest-r11-adm-shared-jvb
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r11-adm-shared-jvb/uitest-r11-std-pg-auth.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgBmkUD6VYMBmWmIYZNqPaC1uqeeWZav6pXgSUarWm3KhRNy3fAaClN6mhHb/vVUCEL46l+qpxIYtkqqemp8hQDvZ9qdbhARM/FvjGErAnWlsExDeTWd0dtU2u+fUe0b+mSuCx22wMkeBTD0Dj7OQuIYNl0+gK8nTgnxTyyf56xkHiDJhR7V0NWofyasuP7W4UeQsbHGw6KvAsEhRlfXkJ4TLyOJ3PqpKwzNeZCPIZG41EUohGg3/sbT9Xj1G0eloddnGrk+HozDp7Qrd3UPWUu+Y3Xd7vLArHiCRfzrfE1z6Z7nI9ulToGMNa+553W7fx7LnYbIhup0LCo4s/+XrToXrRDa3zMsPxiUZ++uCpbIuQuojZuv/g3qOis+f1lXmPKFGI9o7b7jYwPdonUVI8QVqwRsd82WZXo0sX084cB7V3DLWZMLmp8NOYIP78KIEJFo1uwnaIAfdi5KNHC/rebV+FP9iFLR5UR88JDY0B6irJISRd7bk05axJ2WT/Hx5pvHpTMAc+sD/2v9Mp0oCiJ2EuMtdKaft0YmK+mpDEzerZfN/xMxSO34Qa2j4DDQ7CS6b4RDPe1PZrNgasD2MUqzx5EZvv+HBZkG0nHXiPmqO0/T1+Jz9pIXqR8KDsvcAJkkaZOHaCcKQ/HWTHLDX4HLQnGqfZYENBEiaER+HRznwgd77xq+VZJqb797pnRW5JWX68LRs9MEJAx7iKKXNbnoID3/kbU=
    extra_note: >-
      AgAx7ZDQNio2rQHCdkJK3IEWw3rObz1aMdCo4ayIHB0sVavPOdfEzrrxi5nBgBfdfdRy8m4I1ihzIb6Tdi1v1wQF5vJEUy8DPNC8VEqLd+1jCmX2dQmPIhcIJ7a6r/xu9gX6CsW9JDG1oI3zc4zP4FWbB7L/01Likc+InHOLE2kpolfPUtrkG1jpfOalwGs/WbpnsJDhFkFA8+sl3FxxHbaC8Yv/g710AvhV6tGKI+7dZUqsX9fGsNDzActL9pKEhTAwLd9wyLtL+a51csdzDS4yUdjYgcroXQoEVCOTubs4xufgGZWN2jAObn7vRV7lLc4TBZajaeJc4LvRjBNusRsQ+cak5plUlLoYZfpzNEL73JL5YnasdU7Gji4+g8k9mGZszmVcutZMRDa/ODdmbY58ZgQf1BjjZ+NKeungS0CAXcAwNeZ5wDDmxN59vWYtF4f6xsgnmvdr3SXKyLPKnMNa71P94HsCiQpDvQnGVS6O94w2Es3pJaac7e613TfnSaHFBs7ecg53elfEaO9uMbLIxmUbh3J0CxrT4VWF7TV01O3iotn3efP5bSWbz9zk3RFAQ/wnWWoDIyfI8t/jgDa+nJZWAyiVEijSSqqDImqmK+kpQTYkOwYvuSKpQ+mqXzlqt8bRExOm/KyK5x3o6Gt6eaV8EsqN9zyKEzbxKfeOvEI3C1ZrCekoEuO4jzdrvpcHksE1egwYJ/3zjHc=
  template:
    type: Opaque
    metadata:
      name: uitest-r11-std-pg-auth
      namespace: uitest-r11-adm-shared-jvb
      labels:
        managed-by: portainer-idp
