apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-std-pg-auth
  namespace: uitest-r11-adm-shared-jvb
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r11-adm-shared-jvb/uitest-r11-std-pg-auth.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgCYDd3AWTBaerWPUEAnG+/L7nkKCxS98zz8JMIwdNpSVzWBpSDDlkN3unWF9+Z/vNmu9rUfACiZ3a/vOCah3amELSiw5BhwVLyXtXq+sp3dLaWXViU7LVP16977+yYReHXoHocFVFmGJ5Qa6oKqS7yb3XE0yRxMXOBq+rYAha8bRcgrhcBlhWK+456KUlb9g4LM2vq/DZ0Tlp+hr67r2W+PoeNeA8nzB+hyzm2cTZxWnn2mmOk2VK102kGLHAZSHAh0UGoJjCZE8OGr0D9GOqiziDXOmqZR3cdtny9t+HahJTG7LhugNdFzL88CgmMYIs1JSbItUUO3xaTqYmhylyq3Roe/oQAReW+0HgRDCVJapNu3dRJQCIncKqwZZELGTnqFIT2zOQCIE5xYMCX4kpP73bYsT7D+J8Ketm75EDdmcfi0OEhJeHpOxLWRLAotWW0Q7FENhgSXrUfyu195eVtL6Qx3lQ1gp/UfTKjPXQy+eHTNayinRpiC5RuaJeUOP3JTS5vy8UqPhq5I6VPUB0omy2CfLPgASzx88NzhwSLo1plMGCD2GaY9u4j5/TXiMy0YEcq5v2+8eZ1U3DASfG8WoWey4R+m255llKHHgQcBIcCP+yGVqSb3fnWzfJj4QoNbzvtQ81cj3hklyydj5csLsTPNzLPR4JPvS4SJTOpANfqMskJv3e+2DvPmmIan1WfggOHipksHYK6bQYh7vz1zVgupYBoSYLw=
  template:
    type: Opaque
    metadata:
      name: uitest-r11-std-pg-auth
      namespace: uitest-r11-adm-shared-jvb
      labels:
        managed-by: portainer-idp
