apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0925-std-handoff
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-handoff
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-0925-std-tgt2/uitest-0925-std-ns-lc14/uitest-0925-std-handoff.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '25'
    portainer-idp/edge-group-ids: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-0925-std-handoff
  template:
    metadata:
      labels:
        app: uitest-0925-std-handoff
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: traefik/whoami:v1.10
          imagePullPolicy: Always
          env:
            - name: HANDOFF_REV
              value: '2'
