apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0925-std-mb
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-mb
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-0925-std-tgt2/uitest-0925-std-ns-lc14/uitest-0925-std-mb.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '27'
    portainer-idp/edge-group-ids: '9'
    uitest/owner: std
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uitest-0925-std-mb
  template:
    metadata:
      labels:
        app: uitest-0925-std-mb
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - echo started && exec nginx -g "daemon off;"
          env:
            - name: GREETING
              value: hello world
          envFrom:
            - secretRef:
                name: uitest-0925-std-sec
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-0925-std-mb
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-mb
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-0925-std-mb
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
