apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-redis-data
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-cat-redis
    managed-by: portainer-idp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0925-std-cat-redis
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-cat-redis
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-0925-std-tgt2/uitest-0925-std-ns-lc14/uitest-0925-std-cat-redis.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-0925-std-cat-redis
  template:
    metadata:
      labels:
        app: uitest-0925-std-cat-redis
        managed-by: portainer-idp
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: redis-redis-data
              mountPath: /data
      volumes:
        - name: redis-redis-data
          persistentVolumeClaim:
            claimName: redis-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-0925-std-cat-redis
  namespace: uitest-0925-std-ns-lc14
  labels:
    app: uitest-0925-std-cat-redis
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-0925-std-cat-redis
  type: NodePort
  ports:
    - name: port-6379
      port: 6379
      targetPort: 6379
      protocol: TCP
