apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test-secret
  namespace: payments
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: production-eu/secrets/payments/test-secret.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '56'
    portainer-idp/edge-group-ids: '9'
data:
  DB_PASSWORD: dGVzdA==
