apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uitest-regress-secret
  namespace: web
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: staging-uk-west/secrets/web/uitest-regress-secret.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '39'
    portainer-idp/edge-group-ids: '7'
data:
  UITEST_KEY: bm90LWEtcmVhbC12YWx1ZQ==
