apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-builder
  namespace: uitest-b
  labels:
    app: uitest-builder
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: staging-uk-west/uitest-b/uitest-builder.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '32'
    portainer-idp/edge-group-ids: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-builder
  template:
    metadata:
      labels:
        app: uitest-builder
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: Always
