apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r11-std-grp-wkr
  namespace: uitest-r11-adm-shared-jvb
  labels:
    app: uitest-r11-std-grp-wkr
    managed-by: portainer-idp
    app.kubernetes.io/part-of: uitest-r11-std-grp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/uitest-r11-adm-shared-jvb/uitest-r11-std-grp-uitest-r11-std-grp-wkr.yml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '205'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-r11-std-grp-wkr
  template:
    metadata:
      labels:
        app: uitest-r11-std-grp-wkr
        managed-by: portainer-idp
        app.kubernetes.io/part-of: uitest-r11-std-grp
    spec:
      containers:
        - name: app
          image: busybox:1.37
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - while true; do wget -qO- http://uitest-r11-std-grp-web >/dev/null && echo ok; sleep 30; done
