apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r11-std-d2
  namespace: uitest-r11-adm-shared-jvb
  labels:
    app: uitest-r11-std-d2
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/uitest-r11-adm-shared-jvb/uitest-r11-std-d2.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '207'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-r11-std-d2
  template:
    metadata:
      labels:
        app: uitest-r11-std-d2
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.26-alpine
          imagePullPolicy: Always
          env:
            - name: MOTTO
              value: Ça va? «oui» — 日本語 \n "q"
