apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r11-std-handoff
  namespace: uitest-r11-adm-shared-jvb
  labels:
    app: uitest-r11-std-handoff
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/uitest-r11-adm-shared-jvb/uitest-r11-std-handoff.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uitest-r11-std-handoff
  template:
    metadata:
      labels:
        app: uitest-r11-std-handoff
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          imagePullPolicy: Always
