apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-3
  namespace: default
  labels:
    app: nginx-3
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: default/nginx-3.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-3
  template:
    metadata:
      labels:
        app: nginx-3
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
