apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two
  namespace: default
  labels:
    app: nginx-two
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: default/nginx-two.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: 1,2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-two
  template:
    metadata:
      labels:
        app: nginx-two
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
          env:
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: app-db-creds
                  key: DB_PASSWORD
          volumeMounts:
            - name: sec-app-db-creds
              mountPath: /secrets
      volumes:
        - name: sec-app-db-creds
          secret:
            secretName: app-db-creds
