apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/postgres-password.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    postgres-password: >-
      AgBRFJnfmPhbU0fplpjHfmRVluMfvfz7Fhj80nr1bdM+B3PX9U6eJ1tnGGow67v49Ll1JLnyYfb+K0tlldyd1QLMQu500v8r6Ga42EfldU1EHXFTF2E44oS/r75oY7t5SoVlzwALXN3ihC/a2gL1HTpTHejOE3Bei9lweWC+35pA3ivON5F+qNIkodOUjO2jrHddyK9MW64DUj5EmXqz2UA94O6iw2ANoDVorccL5rd8TjGGwrSlvFrWeceXP6Q0uzP6KNXG3LpZbh8olR1gfj5uvSG4ZOSLAiCkiKVRwI9Fjcj9CdJFsarIC7Lm3A+/8Y/uVd6vzNgZba6Zn0x1Q7Pf9xuObKnbOc065KUibt3+bzC/W1prBw9QQ3H+1BB4nT2MvzEM7vOi4P3itdMgpSkA2vy3JhJdr3XFy3wffZ7FRg6HUGO6nv+/bcKx6FCkeE4AhVevD9FyAi+mqwp9hn2zQ2q8tHfvSuwXcaW4XL5YRTCc8kREpsTownn+PonBhdvJ3+r2jCGKsx+8NYNR8S9WO7N10j+LBA1uSuK9AmA/eFOMQzgCV781XxPr+nmwB10jK6VidwHj4STDrNsvnf9VQ0GyZ7g5N+7Mpyo6zFj8V36nXkj2gAy1TZ0tgsz42BsOCF7BsWxQF9x4QEo1a+3myJhH2I8AqMLLSwkIzHsl1IqK3LOcQmj06dZDRFEuBOwiv/regA==
  template:
    type: Opaque
    metadata:
      name: postgres-password
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
