apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-password
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/postgres-password.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    postgres-password: >-
      AgCCcNQLgO7dEwNS7/rb7FN4uJN+LLrNH30+Qup60q+Irv/5h2bOVhfo4pyKbVVOmp4EwAKJ1kQWQNeisX2EcBto5Q/nq8EE3zO/xx6qRxx8qBaQ9XUCb80e0tBP3StuJ3hEbCiV9wh3mhn4WSzC7JWpce317gCb2XomsxsTz/4UskAsVKudqYM0lLQMMOrgKLrn4EsjhRAemLzGYufdNm+yG1UTs7E/2a7DQ2yhQP4BlJsLbpQrR5XDNhyp63P6m4SFVQSKaCfPdL0QB/X5q3ccLe+PThkXpSjvCiB0D9C6GmaN0FhyEiLZH/oF1XttigRR2LXngOVoe/n8bhpqfygJHQ4ZTxdxcSU4mvrzwsIpuwk+yFFefYemjIyhbUH3tVp5FkQANzUWKOTEI3OS7p9z4y8yOhz3q/L4bczP3zFYMfiKhyMD6sTMRsbcyilAj4j7t/Dy6Dtno6daIkjyr7NiJnw2Q90NfgYH6Yb7Ma4i1l4kzXtL2SfP5sSa2E6vyre5QiTdpF8zvA/Juub1QPr5dhzCjv+2J9h9+w6+r1zo0Y6Z7ns8pYQDzmWiUt6gbcl9OCEuqZ0fHZlw6a1djxjPVGwY8hOZEyxrN8gUDArNQPurCenLyCKVQ5hKj7aCuizVR2C0gTp3GXEoH53fJrrQS+VSI87jzrQahCJxEImMlGJgk7OcWbnIabjiKu6DVh7v0e86
  template:
    type: Opaque
    metadata:
      name: postgres-password
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
