apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-out-sec-vhl
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-r11-out-sec-vhl.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgAN6NN03IlyaVhW1b2K50OX8NHknJsTuOxm0w6QQbiL011h2krgnDm33xqz7F02+1SlpUGNUbcS1Q8S0xqxfhzs79Vka39qFlLT7SBTQRSnXfd86KyhgSKVb+6tIuaB0cfNj8B1HLdiA7q0zNXn8f1qrS1b7uR9ZZL4Rk4pHt/ocnXy07d+8a12J3zecJBJGaOfiXOgOKpg8TM3y+mMBPRD6zp9p0dFOgPTq7wRqbqxyDDCwiZY5Pwmn5KKirOrJWU1Lhj53xpslBSjd3zle+V2D3qYK7mDG1fgZRzGLJ4IGTkP/UhUJW6cCWaoO7KR6Dnl816DpBGd+kruIz0lSvi2lIiHECrSfMISSkcCn9wjD7ugFLe1ikHjrDfgxvlXTbzMRFo8DveA9eQ/ru7urbZ8uK2usfwvCy59Mwlz50QpMICrym06PXf9xcryvOo7JFQGyMKyy1G0n3/50WgbF9LCL4nYR+jbf2M06gE8Lu0CwZBk6bYfNE5jCZ6r0FFdq1a5j58jttm9cGn6FMoNNzFzf3NW9vbDZVI219y62p0R58twLVVJO+cLJKFnnXXN8jO5ODK55p2yjQkcw4yiYunSMYPuiIHeBbF/auRXz87H2r+ThoCULpwA3c6oQ95j+0mDRTf9OPRBsF9FwU4oGbpPAHycYn7siaDzbQvH9IOgZnIZYN3R6ahgZvoLyRmVwS0bjI4agw0uwX5C2b3tiEXzko9l
  template:
    type: Opaque
    metadata:
      name: uitest-r11-out-sec-vhl
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
