apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-sealed-legacy
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-sealed-legacy.yaml
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    api_key: >-
      AgBAOSOVrNiDJWv8oLl/5ops6CbjkM1B8wIUnuZGtFTuJ3Q+ov5RSpuWybTC8VZtQ0RnxbvjiSxUKV3lGL0HI1vGFJN0dXoA1MQdOcGT41EcozCH3LCIJuz8l6N+D6/MOeE00JfsZOrJMRiWkGeprBJe5QQmH0yVEvD9H3bFHRod2DRi4/9BlgF4GK7SjRRFzsOKCtd6qGTgxK42P6YHp6BizXwhW1x4hwfhmUAQKH1+KhLV5ycF6EUgLIhI2BD+CnK9UOrbi+7iZrQk/qjaOeplt/l/wCoc7Kclb0McPMzljuOc6KqHAIbtVPWv6LYw+DMsBYITVbhbHMmHKkrMoSmgCLHXfAMHYvuZYdLSjGwoU+dZS3iXWXfIbHMnzX8a3YuPxHxKoMCgnjls350Poz5PKOAJHzBrsxHaSXTOGYYlutM7qyw5vdZP1As8mUYWxwMxZKJ3DdcECDQVPYIiCZnpMrMbCPRyo57bXMccSCd5GBfsQVJsYo5T/1DYt5D9fo8i46+hMTCQDdUze2SOdUXdQaQWHklQzrkvQ2c5c634mq9j2Y7FjoCdodb+Kmoh2LBhnbFmenA/hA8hmR726l9aUJ2t8hkaD0ssn1qHM1LyPgIak57wA2MjEH916jTlQg4VmGSROGOhRsXQQ/3otgabx61UstNTnFgpp5v0+HzBud7WDPn1wERPz4W3G40fpsFexk1fO20cVnMdY7FnaOa92eaaYO71lntPdYHf2wjK
  template:
    type: Opaque
    metadata:
      name: uitest-sealed-legacy
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
