apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-secret
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-secret.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgBLUruxGoEShQF/InmxhzA8gklZpu6pY4lNAxeKReJzG3sLE0HNh7nHQcc9JYpcFzHoYL7aCRJu0Ggj6QsNIkYuJslaMVZTAK0TqNp/M4sS4by0fwGNjuJjzHADQvl5uze63rczTh6ajgZAizcYPrbg67/ybH3+2Z8k4PJjHsxu6gZ3qb8ygh7ks7B545H2sbI1X+CIXmObxfnpkR4isjIKHH89+1aAX0rvU9IxSm72+X2BF587l0hXpC6hSSpSsIHotfSoz7Ywpe0zBxNSUsh6szOcqbChqBorcVZ7WkEngklyeQaLupqxU1h4MbXg89KPbYeUot9M3j3hRt1GRXReOM0wrU2+8dntSh4IphYh2onnM9I1Qala3Hes+cEV5tJxwF7YK1Z219EZFwU1ADM7fh/PQhNjOjrXwYnyD4yMGUoyEFHlh3tCloZc5J2MXN1eb3lnZVkfHhCTSZ0liyMjARTqH/gVcDGJLFQPx1644g0M8EUZQxBEP90+9/OTCjG0uQ5Euk9+HEoewwEgIbk3+8AJtk41R58Yq6I2yqz0LcQ/eOf1l0cjgLOWG7k+AMM50BOIlEXIc4aeUo4p/3ed4E1dXYat9nMXhLGwkBxk7XTFbwhbtLa4oOG7gD6gV+uxL6Xhp5yCVLshbVF3ONYaFn9KXpORbm2oLrfxS9xon/pMQ0m/JxReJW0Pt42ZZxJZ8INdecu0wXZdUTKFbg==
  template:
    type: Opaque
    metadata:
      name: uitest-secret
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
