apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-secret
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-secret.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgCV5X3WDarIXZ6M9M0X/HPXP8mV5czjH/LwpOdKH5tcJh9hmDQGfMp9aMMV6zu0osWC88CRx7kHrqnL2stgb3C2Ic2lY6sk7OewrTbKjja0vgqyV1cj/Xcr6ey/ot60zip92St0szcse0dGrnsOkK5veqnAgkaqmF069ngJdwDIsv86gt1VFAzTWFxfy7gWnvuzs2qpobn4Hbknsgu+Gqy1VmIwhjkPldjfFVn+DHcRNl4B0z7moq1xAF/w30qSGR+07rX7Wl5jC+/J2gz4IBjFN2/bnwWEc2ke0Ic4FJ2kZ3kbv2O95Xl8l27eJ7nUvu0DaE8vG82dn57hduXEm1V8xzTEQ9Tl4lZ8Ig6xWQ7nf4NBVlMxkIYM528/KaiqmD3oHARkxlGHUqS4uohAmft97vWUDR/nECue6/SoMFXEZz9aUSzQpxFEG5fIMPQZhuv0C8u6Ds41Asatoec8CdZ0GneZtoYht2QGFCPlzxlEfI9K70jw1N0JQyyQebmHju4b+LxOHGgFuaNfjcphYCPJXNoEOVmJtpa6j9rGBpb4RyWRnrUqqrmXEhwuJrpVs90Jm8sF9ur+ICz2VQnSeOei6Otu0gWdJqQ8wRBFUcXClW5U3GIK+v8EsM4ihjpxlWPxCnj/UoNd1MPQ+oFpXBHIVNXGeyGoDnIurLIG0GKbEcdabAX57yRuN+pYoVHoXmsRgDyD84E++MeT3UoK1MGgAe2Azbt0
    EXTRA_KEY: >-
      AgAbAFr/zoghxYoo9E8iR9DBXoHW1OpFTcYoBx4iql12ze6yrvqdMBVceZVIs1BPgb2Q8Z0SjUHi+/YS8ha8fmogRkDNWgQ/zI2rdcbW53vAePadrHzDo2KXq+hp6lRdCW7Yk7vNbtRSf5WOOfAtYzW10Dsyqm1sE8PTUsmjZJYfXYNVCuzR00IEr89z7aPX2ws1X3yUzeBeN69ccDx5O22gV6EB6Dp7K0I/l6WjDUEYb2tyxVVamgmmxPsovLPRADEsT4aPTBhqhWoXEGgTacSPdv4gTrHwbo878gD0ybHG/BPvfSVKdhqxjg/3+PwJByeNxu/BjSImwaevtI4P7TDbe4HrsNOeYWKhK0K189nONZ9X7jUUNJeMRhqEoCgDXyqy/l3oQGITPzqraNjl5vYXtTsmuZ3J1lNgLlTGQi5wdo2LPjHT91PML3j0GaIyORQB/IogvK7YSp8lM+/jmXJhuHE4HiXPS1+NmrLfId9nlA5HhjV/uiznDFTSnuRMnP7uvU5PwBH3DzlztXllreMyyXgruyjhzyM6rQIYLpvJCzITiq4OdNoP6S8qXnzM2PK/uJxADY25+3jxgwlDC7O6J5JhOz8ogweDqIHrFdo3OgyXRbaS6qje687WuFr0FBcyYSDnJHZDH1X5D10d13JIsNrbRm/wx3F7qZ4m1PBlZoWbXCeIrQ/rNoJop2neAwN2OonghThA247B9Q==
  template:
    type: Opaque
    metadata:
      name: uitest-secret
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
