apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-out-sec-vhl
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-r11-out-sec-vhl.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgBR7tYXSkJZlZwfxTuDksM7i+vr5ApeXnAIeRyAx4LZA2n6G2si3hLUGIcTAJsgMxxQaaMRNPOheqWWu2QOVwOKSZA9V6O0odgFUl7XNOfrECJZGuw1Z/GOLiyYCYJvFR4W85yhj8X6Cl1vJXQEWjmUwnsjRj4PK/fCfsgq2UEuGpEzURsFd0BiQMcHcl1Zyaf2+xQweqf0ZSN4a5k5vk4xozCPE3DVNVN9x+Me8Njt2Nn2zzhR1/GeYRv827u56itYED0RHykOsAf5O1RI5K1t2Rk0+Q7ukKlp6YRAYja+nHxKQnvS+kVpS4TO5acCIwZv1PihizzK3qhudOZg19y7GJ1jKVC+EdHU1bniMjV6t0xHlVdU8htX4mHVFq+kyngU4J8U689MoQ7oxxIpYeA+OGz/slM6ZiBF7EjiOPShm1EaQeZsufNSceAQVaWz55LzAFXGutgZUz0RUps70rphFYMfxig5WlgdIViDO5xElMtNHZqnTqpDU/3/rVhpTn8s01Ml4Bcxuf265ZpwBplry1ZiT4B7JSio/YrGak9m1g0qpQCO90i+6/dGUq4vCz8ovoHDIi75FsdJObKI7QG+6okBfKlrTsldHp5F05HgiEN9rz9ZDgjRxRvEYooeVoQcRHggbtMs1L1aWF0gC2M507fnitdx9HiFDgVV0TCZYL4Y8z2aqiobaZUn+bfcooeDwZkbJSDKlx9clWyCFf1ckA==
  template:
    type: Opaque
    metadata:
      name: uitest-r11-out-sec-vhl
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
