apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-pg
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-pg.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    postgres-password: >-
      AgBacVYbKwECjDwKo8G0saXZbPiiGI4g6sGflCWKIWRKd1OMGCvxIiSwS3GjKq3mOps5EkVhUQB+XPOXB7Y7+Ld9XytUdR5jXYcIfo0Q23fP1Gik6KbPG1I3H48mVX64fRau9J9WQRKP1AZSJp6mEYCfvjUprTjJkPrHHpLiqF19UMQjEtGY0dB/IuWbEsHtBuvo4J1aJk1wuKCBFFOH2x/qHOt9HUry7EMjAofDlW3blPvu5RaR7b4vCAXIND0I+3SEssXtrkL/II3e2VlWVU5Qv5n/f4kWX8eFC+kiqimH0Go6tHbNLmlMRjt98HSJnyx34EkTZNDl4imct034uPmanq2OvINmIbGyRh+rwTlmpEadoBqaAuI5Pf0e6fyyN0pONtIK+Y7RHg67vkfTUf66sjphlMizRxHHgpY3u6scZOrAKh5AdyNpU2k5qd8V10s2+QEz2jSLVSvHmNVBYM5zPxmHC3JllVkt+UMPrq3Tzan7JzEiJ6pkhN2yM/JPFsYNGGv64knpsXjfTEym2KiXHaytJMXvEHysU2mH+NUlRvUHFoZu58Jdju8XkbTquLsJ6xUQ5bMTlyStnkCykMG5LrOPm6t0KZLnA/T8NLaJX8MWXZ0QY/IQp2th3Rx0j+FrSXpZJGJcg4vchPDW9o7eG5cDZB8LAqx8iDAGH5VvvaD/q8HCk5tvik4wVyl9JKmUlbP46jUxlz7enj3RWHg=
  template:
    type: Opaque
    metadata:
      name: uitest-pg
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
