apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r6-sec
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-r6-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgBf4m2nyzb2bV9Dv4da5rS2crUqOG5rjXGzDVPMc0p0V1xl37k6mVyzHsfw2VskcuRJEYsoPCdt7PYptTq9AmgGpDLUmoe6RnpcIWSdJ4xlZ8jTMv+0VDjAPenBLwPbF+0LsWjf01MEVGjQCriRiCBVkn58XnRcXQcL01UTPc0JSAfp+K9UPsUPFu702UXxoUWYmBKTPOQ66k1OXGEoLg3M04tM6ehu/iFjHTV4YE7NnI1sshr3a4rPYqHG5LjDp7mNIKqe0X/Y4mtKtnnG/v2sFyCHzSs1uA1frWcp8mbqy1gQoq8/ZEge8gMoo+LPyjYNjQX25RzdTjPd8Ko3CV/u+O0bWd06fa7hJzCK8Y3pCoOq4A8kkl61H0PaNWYzWFwuERy5oDXSgTuShrqnI6kkj4loWvlAOVwjk+Vd5o/P/9/XdDp/msmnL1DnHLXtgRMNCukbDWxJb6FWpSR22tHz1TaBDb7BL/6sG1WkQeaFjQg7SRAEaU/gVHrRJ+r0YcbCNjNYxGkDMhq2ZYM6xT73s39EsIxZxZ8NvB1XAItmm+TilC8qfkt1HwlAEViyZVrG7yfMBI+fPo+K212pvjxDLFMS6Nwg0l9WYMsCFdUzU+UhesKEiqKnUPB8Kh8hMSNHBhsgwL8W8h2mrDZJ3NjV9zdkC7mi6pQ9vv69x6Wz4B6ZwcJ1kBgBrkhsRZYJMpUtlR0rzbbfNmxH7kgSG2pjawN8
  template:
    type: Opaque
    metadata:
      name: uitest-r6-sec
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
