apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-1001-sec
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-1001-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgA5oA/7zst6oEphE43tkD6lcYDJphl/ubY34YmGispK6N7ezMJCuZCc0ZlIdaoXd1hiJC/qxOGoy8TYessBoYnhMm6xcOoNJ4++toNCzImB2N2QFysYs1kMU70v+VDIyi2TMFToJCxyWUdtJxEFlIWPkHtA5XIaGb539UXHWJ7TRjfHQ0oNPwMKwAiazX31boCpdVKHWViApSi+6mmS/WnhcH1lAfJcfnI/XD1JKhlDTUxJB/NhHGidohMQFNr9LMvlgQRf2HMDo7O8UQuqnbdS6Kou9ppz1CBFlp05FzToxtUGZPXGj5rNvUnLodlfgSyeJS4azStGLFngFrxhC4Ny7aOGTWsZktLoYoNS2C2Itj5RxTTErvmHrmUWO8JMmFEusuVJ8O8YNyNxDlWYH7w8RDMFq7e5nGOPM3h11W9f/09YmRT4LwVoVdUWjw8Cr25uBqOSh+5DK0w2jF6fKQluKO9lyhlCtl8zP3eK3LLl1uZD93vjNrsRap8ecqD26Gh7ocWjDzZxG/IM+H0eeTaulNL8WR4bpqt31A8mSFCaz+yEezBG/H/jI70q6qsKXz/bhT/H0lm2vTrTuoZtlOTelfxlP52ByQ2NKdSOpyo65w2hEKp2qL4HbjQe41XVc1I7Kf+dWL208sqqa6A79pkRMRHxwdGEBdsxjtRqD+ZIzdDHuBrbQp0vrETq4luzRpwZW/wqIi0gRunB412TdYhtfQ==
    EXTRA_KEY: >-
      AgCufSluYGHDJxOlO8dv8/cDwcBPlGZkVvjIaYJaEBo+nVdSPknvsV2D8wy01+kCRt6KmWAYCeDNgCc78o9E3d7oSGpKELARkl+jwRdCR8U0oWqlfZ27MzOaobG8fV6NztpfpT17IgHiWgkH5sYXxCWzaFmSYj037WHfgrJdafZN7l6dcpGfiwggYpaPrIuMUSGdOfh3uFfF6xZd2MSPY9DF9PrsPGhRKbCK0kv2q1kDlCU2bphGAmMdupFshNA2xcfnwsLKo7REZ8Ho8rsTaiAVwvv9bRkMWz+xQYcLk+Zj4JeYjFc25dZ7MD4JKgl1OBMPcTdAz77gCRWZ52RIuYcN2S/ESuM0mg9fPzKQ+oVVkznpSv8tpJ+BQJMzBc997yZanQgdNVyvE1pTKAc631ZHNHFsRjqoH1KzNGzYiKRfmQTg0HMMq8Agiqcimi31jvGNC825a1u/lGaGoHA6GOhMWoj8j+Y2G+0zoqx2SbZLuZFqUyEgC9QAKiAV+iw8t9Bnu6Lo80KhQu1Yh/zg73EvX5gxopUC0CeY6OGVX1Uw7U6PdUPmQVp9jeUM97aEUse7NLz7kjnotqsvHiWaEurlAIw8RsnxvtlgmrWv0p3y+QUBG6AtAkuN2cBe1jToMa9Vg7nQLPZeZ6w9N3Wk8lGaMF1v16L5Ot3OUf+XZ/F6NeYBoSvAFaCjrwXuFuEOyOdEpSSZ4ZEdIJ4=
  template:
    type: Opaque
    metadata:
      name: uitest-1001-sec
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
