apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-sealed-db
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-sealed-db.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgBeRUBoConOoxQvGSmh4A+sie+QBiG0dhmI8LYwpy8aAtaA6BBb278sZPf3pVorrUrLdo7lBL9fyXFzHYoPS0mS5xxgFIs7LoRYRRiNH3t67U/hbxNhIoEyFoTkEQ0oqo41GQoBlUTgwgdZa1MQdB0jCPhcLt9itQDOnaXbB6aDsZ49+8vPYeyLOcq1BRkufbNcnfKbLw5t2CbUzSlCx2U+TG9HuMUP1Q3ueI6R6wa59uk/tYQ5eUR1iTCxzult+ifGY1RIm3MXj5wyXDOk7V1BxzdqpAzO/kKX+TdGfwGRXOdjVVoqizT+fSYXqyIdLyixgmf69xRH8EdmqeJ8eO2B67qEPtcVHLGjVHDkX50D9WZLodbw/MXW0UL8Bd6WW54EBpryfBF3adKc/wCS6YpB8bXFHk2X9/6069+nENqrWbs/UexsgOISd3yIrEP9OdJSkB6WT1wmo3UxKx+FRSTIwIiDjWkRJtwnfGvjjs2cFIe3oQaxfnSMAaoxQcM/eogW1aVONKkRA4vUgS6t8X20zc15V8NUWHOAoT7J29tBzNRjFQNmTxh+ViGildEzRBwafEW9tJwDTTTlnaTahh8Y8/Ivhl2s8k+wGU8RSpzL+Ii79kB+BfBZdETPMFP0jb4pSVql4uFKIdWDyai3StJUERUFNdkOihfabe971MQezu+zuqg1rjw5RrRrt6goF5yKJqFsZ6/9AdssoWUn7yenENbZ23mhVuKeg34=
    username: >-
      AgAyyMjFTQD60X/N4X2KyzQaGyUITbhzl8frq4xetBV8e7il1h4D8xAWG8HxKwEAy9liOxD1p+DotJCeeyINWXRj5WIrgXnIcHBJ29i7ArADTu7j+XCxYugjeWzSuu2uv/Wv5N58h23Z8Qj8fgbXmLFn0c1t00T6bfCCaJOlhUmjBsksNwp8tv3oSrrYz7nyvnCY0QECohMPTJeql+h6NodEI4+pAZq484vXMwmhP4kiFqRvsCNU+c46chay77NVKKNIIb6TYeZI4D4Vs7r4yf87Ik6yGhq+gxBypr1ocuh7rln2jrKRax5MM/UBl2eTMmXAQvRvh0i5dCcZnGfh1hhLzjm0SGjZLtzvlLN0fIlkwr9y6AB4WbajvfP0e20Z2/93uYH589GiNdJqioQnqEtcWwsxOp9n7EUYFQOIodL0hLS6k/DqUGP/F1yvdC7RAB84ILJrepSoVktB/gDppLIJl4fJlpHpTKAW2DAfVRDKmp0jN17e/5//IBFSYPRkzHOhMWvMeUv/emJ9br1svt5U9jC+ZFefAQgoFVKca3EPkQYCh++bTzOPePZTU+XJv5KX/OLsAxVY7CQRceR2P7aoVbmbAoo3SEeENryGTLoO6ojx0iczufoNA6Q37l1MjSnAFWv8DKE5Tto0P3mN6qEAc9ZNv7d0hYAjt6Es83XS803WbcOhZEWCtOvG+6uijzBFi0nyp17gb83fsh/l
  template:
    type: Opaque
    metadata:
      name: uitest-sealed-db
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
