apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r5-sec
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-r5-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgA5N5HccBZSpRcpIglPRnzn7H3W+BG9d1q2d6gIa/GMzyectdT24zI7zu6XTqSfnK8AjEwznyIXEeGg0sqhltRYhDs2ODhrMyyZvv3bsCs1iiGGWyiuCPt3TwU5oHhw0l8koT39CybOoeA/hl3jtdYX4x6yaqSge/qieIJ0ZsEAJiRMVUSRP23N+n5tXRwmOrFYuOFmOU4xk1s0wkYh+cLouD3aENI1F7ZTWScSgGrqR4AHU25NVEk1arCoU0ddKjWz3J+35lDIqkJnBDnc4p2StNqMHa1Ni0aSwO/Oywrorx6L+2Hp2TPLt+kMz3W4BQkBDwN59RHBDwfy/MaBziKYypZ25Q9C68bmyGzkDgY+ko3Hy9WMjbcSJc1OvBbkzS+RF9w82hW3I6ytsvyOL5zUAFZkSoJeg6esvv2LfhiDXGShWv/QS84e7cLs7nGE+z6/7YUNGMJoKvdgzwX0BNIsj2uX0swxgyGBiYNOPbJd0xK9J13Ofyiy7Hv9EtVwxvtcfVuJ/0xcY3xfpm4kzft5eFp0ln15ti2busqnRWtyqaYNR9zqB/MmD0QK3pJERq2dw52nnzXbbQXKYen/+HrvxMrICtWz3l3/0OGKdkDedbl00IwtCQizNJHKrfM8+BH7Nj5DdlZk7ZKk2qsdDbV721lEue0W/hjSr8uhxKMzLSL0aKqLtHuk1VxlMaUBgwLedgk3MRNI00rB5A1MGEHkQSt1
  template:
    type: Opaque
    metadata:
      name: uitest-r5-sec
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
