apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uitest-sealed-legacy
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-sealed-legacy.yaml
data:
  api_key: bGVnYWN5LWRhZDY0Y2Y0YzUzMzE3Nzc0MzAyMWM4Mg==
