apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-sealed-db
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-sealed-db.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    username: >-
      AgAyyMjFTQD60X/N4X2KyzQaGyUITbhzl8frq4xetBV8e7il1h4D8xAWG8HxKwEAy9liOxD1p+DotJCeeyINWXRj5WIrgXnIcHBJ29i7ArADTu7j+XCxYugjeWzSuu2uv/Wv5N58h23Z8Qj8fgbXmLFn0c1t00T6bfCCaJOlhUmjBsksNwp8tv3oSrrYz7nyvnCY0QECohMPTJeql+h6NodEI4+pAZq484vXMwmhP4kiFqRvsCNU+c46chay77NVKKNIIb6TYeZI4D4Vs7r4yf87Ik6yGhq+gxBypr1ocuh7rln2jrKRax5MM/UBl2eTMmXAQvRvh0i5dCcZnGfh1hhLzjm0SGjZLtzvlLN0fIlkwr9y6AB4WbajvfP0e20Z2/93uYH589GiNdJqioQnqEtcWwsxOp9n7EUYFQOIodL0hLS6k/DqUGP/F1yvdC7RAB84ILJrepSoVktB/gDppLIJl4fJlpHpTKAW2DAfVRDKmp0jN17e/5//IBFSYPRkzHOhMWvMeUv/emJ9br1svt5U9jC+ZFefAQgoFVKca3EPkQYCh++bTzOPePZTU+XJv5KX/OLsAxVY7CQRceR2P7aoVbmbAoo3SEeENryGTLoO6ojx0iczufoNA6Q37l1MjSnAFWv8DKE5Tto0P3mN6qEAc9ZNv7d0hYAjt6Es83XS803WbcOhZEWCtOvG+6uijzBFi0nyp17gb83fsh/l
    password: >-
      AgCdUeF+jzLIkowDI+v+aUgAmmP9fzgxEPniHbENv4x+QP80NhvKAMTJhc/nbU72HkyfllxcKBg/dXb5PoIemK1RU9I8kdnRLK8R2LNUA03wfhh76FAaeu75oV66w0schW9Yvi9TGko9FNcg6iQ8xqFM4TnOnyJZ/d1EVHe3acpCDyQ65gQw5oanYpjlslqCavSL0wNmB+K5QGD76NuwcTr1V8Ms+83NjHdmsHgwta1MRIaHQFc9VvfwRyHQC+OqRxXyHqM0W2rBXGR016gTikLoaJ12X++T1n2kIEdXlTESS5Sf2r3Czd22/OqhB4VaC4Fib9isW0yfuJRw5biu6mRB19XG+5cC8EHfc3wzfoX3IS41f6Qnz2FaZMofHOvxZPPK9vXKy87o1qCXskqJPB379tgSaMDjXzPYZJHjYwDq6ss46d42GNAOAIESdYjub0HbcVP1WHlDSGYrF8u5qtUpMOWJ0mnH4Tr6Cxbofte/o68WBjd8AkutuJOL0VWVjOM1zi2QMY7FdoRmzCXhKJ18MuIOzLFlab+hpudao1eUQKHc3eM9FQDNkMG/EnYl+Kpv4NLDR7w5WV0PXF7J3jiAx87teMOYQekHeqWesPIPJi/ajofRB0bPtwV8XV52/8Y5FOyuaneP8mw52KPre/X5rS65hVUr1RcbvnmwwKGsPQtuVBfWjnN3d1XLsGDVH/wJBA8lTXIoC3K45DYRdoINJ2UrzPSxWFZbpEgl
  template:
    type: Opaque
    metadata:
      name: uitest-sealed-db
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
