apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-out-sec-vhl
  namespace: dev-namespace
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/dev-namespace/uitest-r11-out-sec-vhl.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgBy1EyRGOGO96GWE4Dz1TuvHv63ch7ueJV8+yWeslCC5cx3WT65zuO4Yh5VDLhYd5sooI5G05nJsDZN2Laqpe29Ic36nLfEjiygvvOlEXHN90x4jaMIVveud3YgNxtCkfajn1hwNqZazn1ngbZZEqB46aXtmZLwnxl4xojpUsfBy2z5TSb8pmfaHYSRnp6V9jyyKYLgs2H1oxHutlXkYSZBCYElg+5FR3EyAg3BI/X1bb3g/KAT/vVIxchqklMxtiDWjiuxByhLP1ais011HHBmR4gJja8bK2h+dPr6iL45MqrcihM8s3oAbRAQZreS5KUPtNlW+gOVS4RHHhdi1pMzVMI+WK6WSt/RmcuryTK9BHdcCEOQlD64jQTDHvobfwtOZvmY4oX9G8MYvtnqxL7UZqJ/FQOF3cjCJF3U2o9x+7Gmu2yjNhDOoKWfmBFUXIx4ITbh6i+u/vcHk39tLPdcVUT6pmUq3KPdjVhliXqFx2g34ReDqzh+DxOC/1Ma8otdPab7HvU4dTRdBCeNESXsjovE0tTtbNOZ+JqbqUtb6rWWvtESUOpDyc7PvWwSAvBz/Jcsmg7BB5b7KPE7/xn8OBl+o9/lHIKQqa4Tv67/HndaurP7v316cT1htUiN54sxNReQmdTpRpV1DH7wT+dn7rkuw5paIQbOAiwGlJzDfpZRaCP/MEYxIfJlAHLRRZlrLZPN0b7iugNNbV+NujFb7FtZdTrA
  template:
    type: Opaque
    metadata:
      name: uitest-r11-out-sec-vhl
      namespace: dev-namespace
      labels:
        managed-by: portainer-idp
