apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uitest-0925-std-sec
  namespace: uitest-0925-std-ns-lc14
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-0925-std-tgt2/secrets/uitest-0925-std-ns-lc14/uitest-0925-std-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '28'
    portainer-idp/edge-group-ids: '9'
data:
  DB_PASSWORD: czNjcmV0LXZhbHVlLTI=
  API_TOKEN: dG9rLTEyMw==
