apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-postgres-data
  namespace: uitest-cat
  labels:
    app: uitest-cat-postgres-pgadmin
    managed-by: portainer-idp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-cat-postgres-pgadmin
  namespace: uitest-cat
  labels:
    app: uitest-cat-postgres-pgadmin
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-cat-sweep-0928/uitest-cat/uitest-cat-postgres-pgadmin.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '67'
    portainer-idp/edge-group-ids: '24'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-cat-postgres-pgadmin
  template:
    metadata:
      labels:
        app: uitest-cat-postgres-pgadmin
        managed-by: portainer-idp
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@example.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: changeme
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: 'False'
        - name: postgres
          image: postgres:16
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POSTGRES_DB
              value: app
            - name: POSTGRES_USER
              value: appuser
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-postgres-data
          persistentVolumeClaim:
            claimName: postgres-postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-cat-postgres-pgadmin
  namespace: uitest-cat
  labels:
    app: uitest-cat-postgres-pgadmin
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-cat-postgres-pgadmin
  type: NodePort
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      protocol: TCP
