apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-cat-nginx
  namespace: uitest-cat
  labels:
    app: uitest-cat-nginx
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-cat-sweep-0928/uitest-cat/uitest-cat-nginx.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '65'
    portainer-idp/edge-group-ids: '24'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-cat-nginx
  template:
    metadata:
      labels:
        app: uitest-cat-nginx
        managed-by: portainer-idp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-cat-nginx
  namespace: uitest-cat
  labels:
    app: uitest-cat-nginx
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-cat-nginx
  type: NodePort
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      protocol: TCP
