apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-sealed-db
  namespace: uitest-sealed-ns
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-sealed-ns/uitest-sealed-db.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgBjPtI9Eu4TMbHYNAxmnflP7bY6J5DeIrpe+uDnqyPoT7XZPZ020jzOLn4K0PoFQY6RLS46J/zVT7Y1H0Em0GJ8cpOSYF1K0Zn6kUh2nbAk84bdoxzm+KHPzHCzuZ9gpDN7QxSlSZthVqZaVJzz6yfZcyqP1KH5PALiecxOKsbXZGNun/wSqY+jygeMPp/I26V369VuG4nmjjzLtLMsu6zRYRoUu+mDN1ax7NNR3vXVxk4yoaTaqzMu7C5Udh+A/WqeBB5iwsjrdN2QR2igD7i5itv8NdG+yBUrJhxvSH+Hhr25W4yDjCFbpZo+xCctV9FFh7t9panQlvon5+jedLLh9VovzAJttwb5+KhpdJXG5j1W/vj9F5QwyUdf4YYaFQomKuuOpjNe1n11Rsh2K7gEY44GorLACrGhmml9OCE/b+kCje/fSozwJRrraQ6ehuY/SRvaYcSB9TjQTyHDHyocMtjib31swH07iyBUDj4RTC5Iq3gqHw/wEnS+1aoyJQ2vpMJ9D53qrDlWzmbcLVWCYMWkG68YiolftxReRFR7z+R7OXN9f8KLYn7nLIWbQ6pZtSURYK+Sg8hzPlJG771tGpq7TcgybSdKJ5icIkJnZNYY1HHCrnWFOEWIZLEGXWTARf/fC6AR+GgniHWU2CcdGA9QuO85HIgS0Nzexn3zUAVCuPWPLyjXssOY0SBpf22g3A7ubtQpY770nsPL4l7F4eTmseLpZQkDsJ0e
    username: >-
      AgB+V6HR0n8TNIaA3ZJdbFu3QOiuqm9fG5l16v1xq7YzOytCnKvY+IQ7165cw8uem7Cu0bIeVe4PM4UEtlKtQftKOBmJIb51/byz2dj1wKjTIReYR0WNkBQE4BBWJ5XMZvlfhMCIS2Jy7vJi+5dJNv+25TuYzgCu/SV0TRVAypEvYIWXnfHft6aIsLbW6IsAAm6+aRB4h4VlhtvIS7yAwzpMPPeQS0cf+5BOHcKpMAVUfVtMZw//hDw9wDNCVIvN+LkUtCAEBfd0L5KHRTHJ6oSpwU0FYbzWkspTHTRrJEe723XtNMjxeVL/JeemgeQMOCNV522UQbAbt7DvsHaYG32+KcBjZD6AmkJoEADU5+gtWvf90KJ8sCT7dIV2lgqGsq1hMWk4k50iSQL5zSZNkBWWrWJvSDKDfQNmnLhEkAg6LpKkvzQxTy7G94Hv3nzLlcMAkBWRp2+FLSeW5QWd9SUADZ3vdgz2OOX2MRkWvvZ1WkgYFNgPg8Vvbqi+7tn4Yo2X6qN66c9TSlggcX9HhFcdydN2/MZ2PbA0XYz93pcyMn62ONf9FGoq9SO2H14zXOxFGYAGLizu8A5MJYAhdkOZpP4M2N/nFNhtkvvm2gxyaQ6BCtkxpCwWJXcTj/VltCM304nAYGrVBGfUZ7TF3qe5DjMXg5tozWTlfAhDTi9mbXXnjEBx2A5/DPh3iEZJ1DakRxkkuBb+cvSqYJG/
  template:
    type: Opaque
    metadata:
      name: uitest-sealed-db
      namespace: uitest-sealed-ns
      labels:
        managed-by: portainer-idp
