apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: analytics
  labels:
    app: nginx
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: production-eu/analytics/nginx.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '48'
    portainer-idp/edge-group-ids: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
