apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uitest-g-two
  namespace: uitest-g-b
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-g-tgt/secrets/uitest-g-b/uitest-g-two.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '22'
data:
  UITEST_KEY: bm90LWEtcmVhbC1zZWNyZXQ=
