apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-creds
  namespace: extra
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: staging-uk-west/secrets/extra/demo-creds.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '52'
    portainer-idp/edge-group-ids: '8'
data:
  PASSWORD: eA==
