apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0928r3-std-app
  namespace: uitest-0928r3-shared-k7q
  labels:
    app: uitest-0928r3-std-app
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-2026-09-28/adm-tgt/uitest-0928r3-shared-k7q/uitest-0928r3-std-app.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '17'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-0928r3-std-app
  template:
    metadata:
      labels:
        app: uitest-0928r3-std-app
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:::bad image@@
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
