apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-db-creds
  namespace: default
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: secrets/secrets/default/app-db-creds.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '4'
    portainer-idp/edge-group-ids: '1'
data:
  DB_PASSWORD: dGVzdA==
