apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-grp-worker
  namespace: uitest-grp
  labels:
    app: uitest-grp-worker
    managed-by: portainer-idp
    app.kubernetes.io/part-of: uitest-grp-shop
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-grp-target/uitest-grp/uitest-grp-worker.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '81'
    portainer-idp/edge-group-ids: '25'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-grp-worker
  template:
    metadata:
      labels:
        app: uitest-grp-worker
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: busybox:1.36
          imagePullPolicy: Always
          command:
            - sleep
            - '360000'
