apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-grp-cache
  namespace: uitest-grp
  labels:
    app: uitest-grp-cache
    managed-by: portainer-idp
    app.kubernetes.io/part-of: uitest-grp-shop
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-grp-target/uitest-grp/uitest-grp-cache.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '79'
    portainer-idp/edge-group-ids: '25'
    portainer-idp/note: uitest edit note
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-grp-cache
  template:
    metadata:
      labels:
        app: uitest-grp-cache
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: redis:7-alpine
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-grp-cache
  namespace: uitest-grp
  labels:
    app: uitest-grp-cache
    managed-by: portainer-idp
    app.kubernetes.io/part-of: uitest-grp-shop
spec:
  selector:
    app: uitest-grp-cache
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
