apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0928r3-adm-cat
  namespace: uitest-0928r3-adm-k7q
  labels:
    app: uitest-0928r3-adm-cat
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-2026-09-28/adm-tgt/uitest-0928r3-adm-k7q/uitest-0928r3-adm-cat.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '17'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-0928r3-adm-cat
  template:
    metadata:
      labels:
        app: uitest-0928r3-adm-cat
        managed-by: portainer-idp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-0928r3-adm-cat
  namespace: uitest-0928r3-adm-k7q
  labels:
    app: uitest-0928r3-adm-cat
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-0928r3-adm-cat
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uitest-0928r3-adm-cat
  namespace: uitest-0928r3-adm-k7q
  labels:
    app: uitest-0928r3-adm-cat
    managed-by: portainer-idp
spec:
  rules:
    - host: uitest-0928r3-adm-cat.apps.uitest.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uitest-0928r3-adm-cat
                port:
                  number: 80
