apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r6-pg
  namespace: uitest-r6-ns-q7k
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r6-ns-q7k/uitest-r6-pg.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    postgres-password: >-
      AgAlmlrZoAipyiUOCaX4PnlFSLIIhRzOO8BwetRJLz/JGDJoui5qYhZuaD/GMjSEVaDpRlT1CnEi8ACVEqk/4PSO5jNCPEdL8L6k3GJC079Jn3rv/MsnGMV/x4XSpNwrjkjJR2k3codTXR3YzWjBmIleQVODJbIfboxt8NegPJMaapOileUnLVYboVvop10tugGWm09i/T8j/hdU8Zpf05UCbAH1GnJwOB+fP9w1sy4s4zrBInAAF0R0fsjNlJgGNDX6bf/xedgrgEQ3KvX28HjQzb6h4oIXeuQv3+m/o1/8jx4GjLQJyh6VGUrN1d2vZYD7mrwcY60JV7NejibZg21J5d2uZk8bEN8bex7fdhS7GqTcHXnHpo+hEMu3wMN7D63lsmactRPqlg2PcBFjHcJF90K8pL8aOW0VEQwmBRHzrVMRyMJZ+lPg9icLTQz1NJYeRQ+H6l3Jrh+kLcBtrXVHKXwEBZe/6OaazhejMQiBFbCZJrwHW+o4O+92HOzfA/DcU6haQx6qhVX8VjfsYNB8MR/T3nVzcOpZEyUV6OewVjYtXSsbc/SAHS2w8CFXfgi2oSuwmc50/kGyy1V+OnpBGXMhyZDmO17mdKjGUIHdF1LpdJtUCzOSEdWhwXOUa71Pv/ckWxB9fX7BcjmVfSsf/0N0aIk/cttjn3wR75Z9cGrrGYuPTK4gK5Pgi2ohjClpq3SX9LlhNhKKrxvfMZg5C7ZXdw==
  template:
    type: Opaque
    metadata:
      name: uitest-r6-pg
      namespace: uitest-r6-ns-q7k
      labels:
        managed-by: portainer-idp
