apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r6-sec
  namespace: uitest-r6-ns-q7k
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r6-ns-q7k/uitest-r6-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    API_TOKEN: >-
      AgBENKPmDGvpzQWENZ83XsewEibI/ryASQ5bBq9AvCwTkL7iC49sjNLx0cFPETJAi00uQrCW6S+2HnA+L1ds2KMFwD4Jz+NZvq5GsAcEmGoeRzIVDbz9PobwXq6B8q1hLfuht5rybDC/1BoKm7Sf5XOYfIrqVLNSGlbgkenNvKisGqrEt9x4KSK79fjuO9pJyFqTHs2uXOIlxr7zXKG8SFvarr2nntzIUFbFtyEcPNagNvxeDUVnDngESWeCLEKqYwH8aTEUGmoGWs0KEwzfFhXbb3m3MOLUnllTcDDTtCiGmktIBFQ43yfP3UP1u8FzMcOH3pgxH0YBIdSsSa8ZAxve0BczT2ZEcFvVLp140EoTKQwhwgQNnuGFsbZLKrhLu1+TYhJNtx2Cynb39+fcIIMb9VfhVuAaNNAmbpPWqP+zFuR63v7wygQyFkOxXBam+LT5gLV0zsEn5biy+Q1HagzTNkxnMDCF7kCQZJ0RdTmQS6atdnB0e341zcbI/HPmU5PThBkidDMwBE32NvzOCo10KJ6iETbtRtnoJZTFFqmK3Xy2lFxKa3T4OcrDXkSzXnPtt5iltZxBFYA7h+UYvi2cggbrPTJBtPt0Vlt0AdeQ0Y8WRzAEWQvOLQPorPHazz6/zWvbJJqOI9kDDGdDt9F6D/wNTXvBU5/y9RO10CKNTMU7+jo56T8VeWgPbGXezG+xaTVSx+umryfhgCl3B+ZcGLYr
  template:
    type: Opaque
    metadata:
      name: uitest-r6-sec
      namespace: uitest-r6-ns-q7k
      labels:
        managed-by: portainer-idp
