apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-0925-adm-web
  namespace: uitest-0925-adm-ns-zobr
  labels:
    app: uitest-0925-adm-web
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '2'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-0925-adm-tgt/uitest-0925-adm-ns-zobr/uitest-0925-adm-web.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '22'
    portainer-idp/edge-group-ids: '5'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-0925-adm-web
  template:
    metadata:
      labels:
        app: uitest-0925-adm-web
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: GREETING
              value: hello
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-0925-adm-web
  namespace: uitest-0925-adm-ns-zobr
  labels:
    app: uitest-0925-adm-web
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-0925-adm-web
  type: NodePort
  ports:
    - name: port-80
      port: 80
      targetPort: 80
      protocol: TCP
