apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r7-std-sec
  namespace: uitest-r7-adm-shared-m3x
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r7-adm-shared-m3x/uitest-r7-std-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgBMkcWCUNDnLV8gbJZnvVETvbGue8rS3XC4nP0a7ccBgg5i/L38HiP1KQokb8JuTYAJLbW/L3pQyW7Nqp04X9nIRphu3RRRmGdRHA7n86O0TC8Vk/Gz3Y+wNY/bqaNlKd+S0vUsVBZLg57K9TAGi3GsaSTbAIxN0p0iMU3Oog0/MSV1q+1HfrFp0XBncvfwirO3wZ1OqeFcCKz72K+BfTwYD3mY1z2Ai2DCRIdwCcdogmcIyt454lTagvHB3J0JoTXvwMHxujZls2J+BZo9Vav1m0hApe0pjWFTjqMbnwEyJ73cInft6nef+xp6e+a6hvGXY/jFe77eZWAVuW5iuejX8GBUhzApieGE/XaE1oNDCoYdhGHilwrLiVfBhSZtrYzChhYrtcE/cG2phr6UpKLYLaUEJ8y0LOhxN5ZlXX5WBk9ddVrX0tEoxE959uyFD5EO/75PLaPhz62N13Q1o5ekrrqYMM/n+varS/iKwMeFXB9wngg3QrWK6VgblXIDw3xpBGoP9MQ3Jn2gb5g63BEHnQRh4clWi45QWO5J3Cjf6mY5vx0ephV1qkeOVlcgEoxW2gKZjLZrhAx0GUOrLJZWuJ9OJWHY8+OTaoAM9AcYJ9nfCgY3HEjWewz8HbQz3Sm9H8rJeYFv+Np6xUnyu0rK6wJ8Asi1CE1ITiGSbs5CHrKeRzJwAPLnyitbc/2eX4i2O0CN42aWl/Q1WcLJhzTaUg==
  template:
    type: Opaque
    metadata:
      name: uitest-r7-std-sec
      namespace: uitest-r7-adm-shared-m3x
      labels:
        managed-by: portainer-idp
