apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: uitest-r2-std-sec
  namespace: uitest-r2-std-b-hzzb
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-r2-std-tgt-zohu/secrets/uitest-r2-std-b-hzzb/uitest-r2-std-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '13'
data:
  WHICH: bnMtYi12YWx1ZQ==
