apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-2-auth
  namespace: team-a
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: qa/secrets/team-a/postgresql-2-auth.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '27'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    password: >-
      AgBSmFGmny88aCGNnvMP5IhZ+UJVERB67XAuB1rARLuOZS8TLwQ0HJznzxUZ6u50aSTIhQJYdBmTTeAhUWP/7InMKq34+z/MzrSZBDmK3DbYAYIxaylBOO6k7Z4bSlvUQUJIRgqENggmQtTWOZLwSjYaXnJQFANQ8F3c31WBuZFawqPmJtwRKWyOlVaiVwjmvf2y6MghvQsjJlv4WPzwNJWLY3IvIf8lqbtselZPoqjXONhBAMq2ROQigtscGXhtuoCS159BKKO5hWF7HdKPsVEv+Sch67I4+nzkc2GKvkoyvACovcviUTW9t/6Ed5Sum5Z1eYqOnMr+9pRsWS/PKKj1EFO2dQ8p2WtP7Qi1VYZKWNhl2JWCJGl32xTR/4lsHOWOYqTOcOQQeLiS2lqmHdVbHRAdpVHxwwlGE37haXnIsg1L0S4TxagoIB7iiVga8bAUwJGwwris0gfxX0RwT5cQp3uvqE5odUkng2Gr2DYdvRs2HjMVCdNSNizBtdKHWV4YXmv6A6/K5keobRQmLHNhNqXAT99dEzlTSeXNgz3laaVoD6oUks/muVBZBpjnoXQkdjakPCVdPjPlTc8p7tAfHnVr0qCS/AkGFLb3cc/mNJQCARap/CkUtbfX3LV5gr+F/Xmn45RfCw7BGrN+AOivlbOYHcF5KjPCKAUUO6hCMeSbX+JpTVaYoq6yM73TWT+DW/B3HMufhuW78/dH74YrjSX8B2a72ts=
  template:
    type: Opaque
    metadata:
      name: postgresql-2-auth
      namespace: team-a
      labels:
        managed-by: portainer-idp
