apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-with-secret
  namespace: default
  labels:
    app: test-with-secret
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: idp-apps/default/test-with-secret.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '7'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-with-secret
  template:
    metadata:
      labels:
        app: test-with-secret
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
          env:
            - name: TEST
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: DB_PASSWORD
