apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-sealed-app
  namespace: dev-namespace
  labels:
    app: uitest-sealed-app
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/dev-namespace/uitest-sealed-app.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-sealed-app
  template:
    metadata:
      labels:
        app: uitest-sealed-app
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:alpine
          imagePullPolicy: Always
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uitest-sealed-db
                  key: password
