apiVersion: v1
kind: ConfigMap
metadata:
  name: uitest-r6-probe
  namespace: dev-namespace
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/dev-namespace/uitest-r6-probe.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
data:
  k: v
