apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: uitest-1001-cat
  namespace: dev-namespace
  labels:
    app: uitest-1001-cat
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/dev-namespace/uitest-1001-cat.yml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-1001-cat
  serviceName: uitest-1001-cat
  template:
    metadata:
      labels:
        app: uitest-1001-cat
        managed-by: portainer-idp
    spec:
      containers:
        - name: nginx-statefulset
          image: nginx:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx-statefulset-0
              mountPath: /usr/share/nginx/html/data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          ports:
            - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: nginx-statefulset-0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
---
apiVersion: v1
kind: Service
metadata:
  name: uitest-1001-cat
  namespace: dev-namespace
  labels:
    app: uitest-1001-cat
    managed-by: portainer-idp
spec:
  selector:
    app: uitest-1001-cat
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
