apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r6-close
  namespace: dev-namespace
  labels:
    app: uitest-r6-close
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/dev-namespace/uitest-r6-close.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '146'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uitest-r6-close
  template:
    metadata:
      labels:
        app: uitest-r6-close
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.27
          imagePullPolicy: Always
