apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-5
  namespace: test2
  labels:
    app: nginx-5
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: command/production/test2/nginx-5.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '16'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-5
  template:
    metadata:
      labels:
        app: nginx-5
        managed-by: portainer-idp
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Always
