apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-std-sec2
  namespace: uitest-r11-std-ns-wpm
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-r11-std-tgt-kqz/secrets/uitest-r11-std-ns-wpm/uitest-r11-std-sec2.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '43'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    TOKEN: >-
      AgAzRYdr1ANGykoBS7/Vp2BC7/7zwCTnjN1bl3HOhB4ow8TCCbnvdEtgHWs5JEl+v9JZSr+ZItKBeG43OKiACNwXn6rKp6wR93Dzcnrgma6dHdtr6y355OQYev6jJ3WGTLMz8wCa3Wp/wS1XG1I9SwrVd9/JKV1gG7BR9AalOazJbLATv+EtErL52NYhiLbUXv6mn2Ci5u9k7dR4gbVPs07B9+WZxZQGU8ejM8R/ZcV4IeDl+pw/iUelG75Xoxbfvcbna7thYbYY6E4SAaai7xDhBzy31XRi6LqH+/mfgkiMeBsioFgolDjKW9eci9kJ1rZRCh4fXZqoGOOdZuQF4AdF81pUtEwSfi+Bj2y7tbmAObulQ9EzXmYA2CnqU0Ymcu+0EDOetQI/yophKAYkskFqGGigLraO51Hat2gC/D9782okQrnqxLvZ/WlAvykMl420Gadyj3FtPXoqMPIq5axP21QSHwl4qg9VmXh1pxEhDEyc71i5rGpyPwfFi3l6hLq/zKV6Ptkl0G2TKTvLzCUS/cVocbnd0lILs8tPnwkBQEeM/fVG9aoIh+/ZF6zfSRgYyVsEBr7reN+s5SwEGLUGmhSEU65tKwGeWiAeRHl1LLwEGzX4edtT/sCIZ3IipQh5Kc68cr1GE8Uvi4ZTVY+ENkzUZabv51fO/Kmsu5otlwn9UovZvYXvxfqXsgFDXkRoTynEfNkqmvBUAigvG4WRgzlM9WU/ulf52A==
  template:
    type: Opaque
    metadata:
      name: uitest-r11-std-sec2
      namespace: uitest-r11-std-ns-wpm
      labels:
        managed-by: portainer-idp
