apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r11-std-sec2
  namespace: uitest-r11-std-ns-wpm
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: uitest-r11-std-tgt-kqz/secrets/uitest-r11-std-ns-wpm/uitest-r11-std-sec2.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '43'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    TOKEN: >-
      AgCJ6Xd9iTiZa5Y/QcZ28/r02LgxaRknHq/8Slpo71oPXvdnVEbVzcxHIccgzxapYz/3u84aeaV1GJUEW+BhS3uieUd4UZB5GLMRdIkJNLbgCZeiDX7V7EydqFtU0Wx30vLovnhu3ZI6+k2Ancr7KaWQQYLdnpfCTeMkvPNnfCccNmPPAIp9LDMA/oMQ/k2EL/CD5IIL8XQZoq/uEbCm1H+53TzD4oDqvi9N/Sss3H0dSzBOzSzrXuTbGrWhiIIGLRzXDirP6Ee6DDR6qrKyOCHi4YDaLefgNtR3mmQbYdTJ/m6aS0dc3I72db04+qJez9+ibY5Lot+RzIgHnIdQCI6Cfr7hFz6RXScUnoEhn5kc9jfEoxa2XlfYlWo8JPEK8I3IKEazZl9CRiV7M59Clga54r5qfS1qnQAkm7S0FL90bVjWFwgu1TSdTfuqxM3nEbumTeREfxVGn90onywms4rNKAx4Q+RN2qWg1Fm7CKaoAUy3vPmOjtQk51nVNBBVU1GMQ3LtypLKKw6NE6Eo4fb6cFUnKe0cBuzmbmBDkaUn7Hx5VPXLo2RN0Abl5B+mm/uhntYZgfKxNHUuuD/yxaJsy4w2UIPS62QSZ54wljncTt1yPUSGzmn6wvxny88SQSjadDTcWxBQgm0kfj3sesSacMGdipiYqJ0f9CtEHmWXdSnP+SKeuySd64BnxuCSGW/VHMw7PHxxNKi0PhgHkMJjoFizcmQZzD/N5g==
  template:
    type: Opaque
    metadata:
      name: uitest-r11-std-sec2
      namespace: uitest-r11-std-ns-wpm
      labels:
        managed-by: portainer-idp
