apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r10-adm-sec
  namespace: uitest-r10-adm-shared-wqz
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r10-adm-shared-wqz/uitest-r10-adm-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    token: >-
      AgBubnc+/hkXWoErHM/k6LXwTHS8p2Wooc9LoDlRnuGXpJCmBPfzDGq3mkj6z1g+0j4ZPrLipAaSHfs7exRE1uOAj0Y12Psowli58MF/AcRGJO838m1KGujtd4zSLBcZQ09wRYIt4Z12xqRqL7rBEexp4v1pG8cQu4j1V6Rj88Xbx6WmE6WmEZA2Nt1v0+Xnbx8MofpI/GgaPJxWg4gr97roo94hAYQofd+P+DTe88jw4nUcWNTgLyb0f319nHerWhLvxpF3CmrDR+UvOAN8OsuHuTqd6yC2pMUpbDpYT0wAZHwfj/yKtLLxoJmNlXDClnBi0IkWD7fwRdE9y22gYxV38T4g0KqjcMCwywmp4nAwmt/PukHzkm4vFZnInRu+DMJQWz3ZAqsEr5i81hPkGWz24zOdvWJt+Ex4XIO3BlQZlz3FRWmYw9xe0cTLzVlEyixIB/5s4OqQ/P84GzbkuoNcxEHyRoKcxht0wIf40u7/0wVoIGXy50vp4cMCvg/Ip1ky1yFkbXesTzTgp9eV0X10r1X6BiblZ3zUAujUBNymNUq2XurzJodZPqmgzske+DEbBOqMXAEXHm1H9DLB3Tg0Kyo4eWNhKMDK2HMKoRAN2Xq6Oa7KM3dWXtVb9+TR6v50RqX1hceI/eOJPx0PNmsYbAKFn3qMKJW2IwGroG3sAD4N3+MxFq07ZGEKeXbBoq4T+e4l6XwoqHT6GYDaQoU9N9Jx
  template:
    type: Opaque
    metadata:
      name: uitest-r10-adm-sec
      namespace: uitest-r10-adm-shared-wqz
      labels:
        managed-by: portainer-idp
