apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r10-adm-sec
  namespace: uitest-r10-adm-shared-wqz
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r10-adm-shared-wqz/uitest-r10-adm-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    token: >-
      AgB0TsBnnXYtZDP4hXKlscuaX2v40+mdDpy6i476u7Q6VH+3pREfJD0f1PMH1Zx/tE/kBjbcotYrVV7NVA0beYT5NP61luzU0yt+VWRUuARwOcYE7ky1mBFfj1e/crkET2MEDhV7s7pv1C8JMcjID6me998LBm6k3tkxM34LLB0ogBiiKtDH/V8FY6n+B+xxWVeT/2Y1L7QrUJMvOZVDpZpfEHVwPYHnvr4D3ZY25/NvoOJ0AwdjL2Di9k6dDt34PJvfb+6cfUlS8Pzc1Y6+Bc4a77uPpgnXVmYnaE/FHw6pVqoS71fowQOFizdfmupsr1Hu5+1Rgr4A697IlWxIF6gMf7nfZgdmGM6TagLOasFliRRq1Iq5TvhMVmp3GPfbGghVhK6VfOaP/P6wUV5e88ZUSUbdmWZNmmIwVEBPasj+w5Z2bzlPoh1JZdsJpQqSETSZF2/r+YD/USK5n1xjCcHyI+11xfiAdHM/v26Znf/dL/c32pNIfwYoVpMUvmDZb5e1o8RyL5Qw7+ApJoJ2qNqROJYVQbfiK1zHrkea5hy++aBKrXMn3l1aif1fMyoX+j7xuHErIDJ6b+RQqUnUZ9XBGHMh6TXLQ4QLjv7Q6lO2yGkuehDqNCCg5TbZEIwK4qJcxL31Yb6cuX/8HrGlksr5JRpO2J6aPaxByOSJVy4uKYCEhqoNKEgkzAvPwaTRR545YK5zOsbtDSiJeAHCWUbILAe3
  template:
    type: Opaque
    metadata:
      name: uitest-r10-adm-sec
      namespace: uitest-r10-adm-shared-wqz
      labels:
        managed-by: portainer-idp
