apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uitest-r10-adm-sec
  namespace: uitest-r10-adm-shared-wqz
  labels:
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/secrets/uitest-r10-adm-shared-wqz/uitest-r10-adm-sec.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
    portainer-idp/sealing-cert: sha256:650842cfa31162181aab2052d180c2183806a85909b57a39a39f773e694d4157
spec:
  encryptedData:
    token: >-
      AgA8NFAO8GogLpSaBMLP/n5f+VNbAgaSW8z8KBYTmYRQmEeglrrR/AYuzcSW/ifNZodKCwPG+ZctP7lKIqbFXNdHesHLPKijpUEa5qQ1oADH/ME86Y7SvNEWom47rVACt56wwTamfMjqfnWcl6D5BKkDw371WgdEnv8UfK6IPLrzdnToYsOs57p2Hn3Yrp4l9wpZUPO3N5zh4J6eIWKOLV2zYtwKgo3hbkKFkyZIv9agQyPG1TfjlGsKeFWRPYpN4+N6lsICqhQ02u8NbWatkMnR1jGopww1mkbMYzZGpQnq5OwFDCprOv8XD8h821zOrB6YY318g1sUe5U1Kqy8d2IYKyGnzXIXguGv7kjQaeYc0IqjJGBq4EvKz1Z3/TtTqUFpFd9WNYkWkBjJ7CbWovF6JulZXnGb1K+MwMEN1z3Uz2eSfTOuCztbfSFQNt+5DXAoVSnGBa/VAFgLHFTSIcN7pT8lq7Kq1YNM2Bmw0BHCAESiz77lrUPQRnEC/OO24bXOJbJHUHhV1X8ez2qgbBlYuBhUO0Ul218lZ3Z952ceb9w1HtTe+4efEvb7lmo1s7aK+yxIlz4JWpEX7yIN1WTSsmnj4xS/vqB1YH2ow4Vqi1wl0Zo9I/w1CltYwqkAXid107FCj+rjig8trRyJaWB+P2MM4lrnhSBXD6BPY6tW/hdtJHSKoqzkKaWvJlSy+bypPSnwdqCbfe4V/ORHfdFGrZv2C9M=
  template:
    type: Opaque
    metadata:
      name: uitest-r10-adm-sec
      namespace: uitest-r10-adm-shared-wqz
      labels:
        managed-by: portainer-idp
