apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r10-adm-handoff
  namespace: uitest-r10-adm-shared-wqz
  labels:
    app: uitest-r10-adm-handoff
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/uitest-r10-adm-shared-wqz/uitest-r10-adm-handoff.yaml
    portainer-idp/deploy-type: manifest-builder
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '191'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-r10-adm-handoff
  template:
    metadata:
      labels:
        app: uitest-r10-adm-handoff
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          imagePullPolicy: Always
          env:
            - name: R10_REV
              value: two
