apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitest-r7-adm-canary
  namespace: uitest-r7-adm-shared-m3x
  labels:
    app: uitest-r7-adm-canary
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: development/uitest-r7-adm-shared-m3x/uitest-r7-adm-canary.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '26'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitest-r7-adm-canary
  template:
    metadata:
      labels:
        app: uitest-r7-adm-canary
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          imagePullPolicy: Always
