apiVersion: apps/v1
kind: Deployment
metadata:
  name: another-one
  namespace: default
  labels:
    app: another-one
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: my-apps/default/another-one.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-group-ids: '14'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-one
  template:
    metadata:
      labels:
        app: another-one
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
