apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-new
  namespace: default
  labels:
    app: nginx-new
    managed-by: portainer-idp
  annotations:
    portainer-idp/git-target-id: '1'
    portainer-idp/git-branch: main
    portainer-idp/git-path: idc-apps/default/nginx-new.yaml
    portainer-idp/edge-stack: 'true'
    portainer-idp/edge-stack-id: '7'
    portainer-idp/edge-group-ids: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-new
  template:
    metadata:
      labels:
        app: nginx-new
        managed-by: portainer-idp
    spec:
      containers:
        - name: app
          image: nginx
          imagePullPolicy: Always
